{% set name = "MicroED tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.1.0-dev.10" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ tarname }}-{{ version }}.tar.gz
  sha256: 8870aaed97e9d11cc8cb1a7e1252bdb9db8a19b2fbd71e023e8c21f857c7b341

build:
  ignore_run_exports:
    - libxml2
    - numpy
    - python                 # [unix]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib('c') }}      # [win]
  number: 1
  script_env:
    - USER                   # [unix]
    - USERNAME               # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake          >=3.24,<5
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython         >=0.27.1             # [build_platform != target_platform]
    - docbook-xsl    >=1.79.2,<2
    - flex           >=2.5.34,<3          # [unix]
    - libxslt        >=1.0.32
    - make                                # [unix]
    - numpy                               # [build_platform != target_platform]
    - pandoc         2.*
    - pkgconf
    - python                              # [build_platform != target_platform]
    - winflexbison   >=2.2,<3             # [win]
  host:
    - cython
    - libarchive     >=3.0.2,<4
    - libiconv                            # [win]
    - libtiff        >=4.5,<5
    - libxml2-devel  >=2.6,<3
    - nlopt          2.*                  # [unix]
    - nlopt          >=2.8,<3             # [win]
    - numpy
    - python
  run:
    - python

test:
  imports:
    - pysmv
  requires:
    - coreutils                         # [unix]
    - m2-coreutils                      # [win]
    - m2-sed                            # [win]
    - microed-data >=0.1.0.dev9,<0.2.0

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert electron diffraction sweeps to other formats"
  description: |
    The MicroED tools convert contiguous sequences of electron
    diffraction images, or MicroED sweeps, to the Super Marty View
    (SMV) or tagged image file format (TIFF).

extra:
  recipe-maintainers:
    - hattne
